pantos-io/validatornode

pantos/validatornode/business/base.py, pantos/validatornode/business/transfers.py, tests/business/transfers/test_submit_transfer_onchain.py, tests/business/transfers/test_validate_transfer.py
New business logic function and related Celery task for the primary node to submit a cross-chain token transfer after its successful validation to the destination blockchain.
=> [PAN-1870] Introduce on-chain transfer submission task

.github/workflows/docker-vulnerabilities.yaml
Additional GitHub action to check Docker vulnerabilities.
- Closes #
New QA action should run after merging to main.
A new security tab will appear on the security issues tab.
=> [PAN-2003] Add docker vulnerabilities analysis

debian/changelog, poetry.lock, pyproject.toml
Bump version to 1.8.2.
- Closes #
NA
=> Bump version to 1.8.2

.github/workflows/sonar.yaml, configurator/DEBIAN/templates, docker-compose.override.yml, docker-compose.yml
Adds back a missing template that caused errors while installing. This wasn't triggered on CI as we're forcefully setting the DB non-interactively.
- Closes #
=> fix: add missing debian template start services

.github/workflows/ci.yml, README.md, configurator/DEBIAN/config, configurator/DEBIAN/control.template, configurator/DEBIAN/postinst, configurator/DEBIAN/templates
Removes signer key leftovers as the validator node is not using it.
- Closes #
=> fix: remove signer key leftovers

.dockerignore, .github/workflows/ci.yml, Makefile, README.md, docker-compose.override.yml, docker-compose.yml, linux/scripts/pantos-validator-node-celery
Enables `docker swarm` use, with instructions added on the README on how to run it. 
- Related Issue #PAN-1832
- Closes #
=> feat: PAN-1832 enable docker swarm for concurrent local deployments

Makefile, pantos/validatornode/blockchains/ethereum.py, pantos/validatornode/business/transfers.py, poetry.lock, pyproject.toml, tests/business/transfers/test_submit_transfer_onchain.py
This PR improves the retry resilience for on-chain transfer submissions and increases the gas available for submitting a `transferTo` transaction (which is necessary due to checking multiple validator node signatures now).
=> [PAN-2082] Improved retry resilience and increased gas

.github/workflows/publish-docker.yaml
Disables live reload on release
- Closes #
=> fix: disable live reload on release

debian/changelog, poetry.lock, pyproject.toml, sonar-project.properties
Update validator version to 1.8.3
NA
NA
=> fix bump version to 1.8.3

.github/workflows/publish-docker.yaml
Restores the ubuntu builder to build multi arch.
- Closes #
=> fix: restore ubuntu to build

.github/workflows/main.yaml
Removes previously used arch parameter on main workflow
- Closes #
=> fix: remove arch on main

docker-compose.yml
Uses swarm deploy restart for third party services.
- Closes #
=> fix: use swarm deploy restart

Makefile, docker-compose.override.yml, docker-compose.yml
Runs and stop docker in parallel using compose (faster than swarm).
- Closes #
=> fix: start and remove docker in parallel

.github/workflows/main.yaml
Adds missing needs flow keyword.
- Closes #
=> fix: missing needs key

pantos/validatornode/celery.py
=> [PAN-2147] detect all celery processes

Makefile, README.md, debian/rules, docker-compose.override.yml, docker-compose.yml, linux/scripts/pantos-validator-node-celery, linux/scripts/start-web.py, poetry.lock, pyproject.toml
Adds dev mode to the app, so that development can happen whilst the app stack is running. To activate, just run `DEV_MODE=true make docker`.
- Related Issue #PAN-2112
- Closes #
=> feat: PAN-2112 development watch mode

linux/scripts/pantos-validator-node-celery, pantos/validatornode/celery.py, poetry.lock, pyproject.toml
Sets a maximum timeout for celery
- Related Issue #PAN-2094
- Closes #
=> fix: PAN-2094 limit clery maximum timeout

Dockerfile
Adds missing license metadata
- Related Issue #PAN-1840
- Closes #
=> fix: PAN-1840 add missing licenses

pantos/validatornode/blockchains/ethereum.py, tests/blockchains/test_ethereum.py
OpenZeppelin's EIP-712 base contract expects no salt at all instead of an empty salt.
=> [PAN-2254] Remove salt from EIP-712 domain

Makefile
=> fix: force bash shell

Dockerfile
Fixes missing wheel after release pipeline changes.
- Closes #
=> fix: release pipeline wheel

.github/workflows/release.yaml
Include `api.github.com` in the hardener whitelist for the release process.
- Closes #
Test with a new release process.
=> fix/whitelist api.github.com

.github/workflows/release.yaml
Whitelist `*.github.com` for release.
- Closes #
=> fix: whitelist release

.github/workflows/release.yaml
Add ghcr.io to whitelist
- Closes #
=> fix: add ghcr.io to whitelist

.github/workflows/release.yaml
Move release CI into audit mode.
- Closes #
=> fix: move to audit instead of block

.gitignore, pantos/validatornode/celery.py
Point celery to the certificates in order to be able to verify SSL certificates of a broker.
- Closes #
=> PAN-2270: Point celery to certs

.github/workflows/docker-vulnerabilities.yaml
Update trivy to 0.29.0 to fix access to the vulnerabilities DB.
- Closes #
=> update trivy to 0.29.0

README.md
The minimum system requirements have been added to the `README`.
=> [PAN-1973] System requirements

pantos/validatornode/business/signatures.py, pantos/validatornode/business/transfers.py
We now explicitly log a missing validator node registration at the Pantos Forwarder.
=> [PAN-2347] Secondary node as invalid signer

validator-node-config.yml
=> feat: add sonic blaze rpc

.github/workflows/ci.yml, .github/workflows/docker-vulnerabilities.yaml, .github/workflows/main.yaml, .github/workflows/publish-docker.yaml
Uses the Github Actions backend to handle the cache instead of a leveraging the local cache
- Closes #
=> fix: move docker cache to gha

validator-node-config.yml
=> fix: update sonic blaze chain ID

.github/workflows/docker-vulnerabilities.yaml, debian/changelog, poetry.lock, pyproject.toml
=> Bump verxion 2.1.4

.github/workflows/build.yml, .github/workflows/publish-docker.yaml
Avoids an additional line break
- Closes #
=> fix: set cache on same line
